name: NodeJS App Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  container:
    name: 'Container'
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
        
    steps:
    
    - if: github.event_name == 'pull_request'
      name: Generate build numer
      id: buildnumber
      uses: einaregilsson/build-number@v3 
      with:
        token: ${{secrets.github_token}}
    
    - name: Check Out Repo 
      if: github.event_name == 'pull_request'
      uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      if: github.event_name == 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Set up Docker Buildx
      if: github.event_name == 'pull_request'
      id: buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Build and push
      if: github.event_name == 'pull_request'
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./app1/container
        file: ./app1/container/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/app1:${{ steps.buildnumber.outputs.build_number }}
    
